// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: gpio.proto

package gpio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GpioPin int32

const (
	GpioPin_PC0 GpioPin = 0
	GpioPin_PC1 GpioPin = 1
	GpioPin_PC3 GpioPin = 2
	GpioPin_PB2 GpioPin = 3
	GpioPin_PB3 GpioPin = 4
	GpioPin_PA4 GpioPin = 5
	GpioPin_PA6 GpioPin = 6
	GpioPin_PA7 GpioPin = 7
)

// Enum value maps for GpioPin.
var (
	GpioPin_name = map[int32]string{
		0: "PC0",
		1: "PC1",
		2: "PC3",
		3: "PB2",
		4: "PB3",
		5: "PA4",
		6: "PA6",
		7: "PA7",
	}
	GpioPin_value = map[string]int32{
		"PC0": 0,
		"PC1": 1,
		"PC3": 2,
		"PB2": 3,
		"PB3": 4,
		"PA4": 5,
		"PA6": 6,
		"PA7": 7,
	}
)

func (x GpioPin) Enum() *GpioPin {
	p := new(GpioPin)
	*p = x
	return p
}

func (x GpioPin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GpioPin) Descriptor() protoreflect.EnumDescriptor {
	return file_gpio_proto_enumTypes[0].Descriptor()
}

func (GpioPin) Type() protoreflect.EnumType {
	return &file_gpio_proto_enumTypes[0]
}

func (x GpioPin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GpioPin.Descriptor instead.
func (GpioPin) EnumDescriptor() ([]byte, []int) {
	return file_gpio_proto_rawDescGZIP(), []int{0}
}

type GpioPinMode int32

const (
	GpioPinMode_OUTPUT GpioPinMode = 0
	GpioPinMode_INPUT  GpioPinMode = 1
)

// Enum value maps for GpioPinMode.
var (
	GpioPinMode_name = map[int32]string{
		0: "OUTPUT",
		1: "INPUT",
	}
	GpioPinMode_value = map[string]int32{
		"OUTPUT": 0,
		"INPUT":  1,
	}
)

func (x GpioPinMode) Enum() *GpioPinMode {
	p := new(GpioPinMode)
	*p = x
	return p
}

func (x GpioPinMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GpioPinMode) Descriptor() protoreflect.EnumDescriptor {
	return file_gpio_proto_enumTypes[1].Descriptor()
}

func (GpioPinMode) Type() protoreflect.EnumType {
	return &file_gpio_proto_enumTypes[1]
}

func (x GpioPinMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GpioPinMode.Descriptor instead.
func (GpioPinMode) EnumDescriptor() ([]byte, []int) {
	return file_gpio_proto_rawDescGZIP(), []int{1}
}

type GpioInputPull int32

const (
	GpioInputPull_NO   GpioInputPull = 0
	GpioInputPull_UP   GpioInputPull = 1
	GpioInputPull_DOWN GpioInputPull = 2
)

// Enum value maps for GpioInputPull.
var (
	GpioInputPull_name = map[int32]string{
		0: "NO",
		1: "UP",
		2: "DOWN",
	}
	GpioInputPull_value = map[string]int32{
		"NO":   0,
		"UP":   1,
		"DOWN": 2,
	}
)

func (x GpioInputPull) Enum() *GpioInputPull {
	p := new(GpioInputPull)
	*p = x
	return p
}

func (x GpioInputPull) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GpioInputPull) Descriptor() protoreflect.EnumDescriptor {
	return file_gpio_proto_enumTypes[2].Descriptor()
}

func (GpioInputPull) Type() protoreflect.EnumType {
	return &file_gpio_proto_enumTypes[2]
}

func (x GpioInputPull) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GpioInputPull.Descriptor instead.
func (GpioInputPull) EnumDescriptor() ([]byte, []int) {
	return file_gpio_proto_rawDescGZIP(), []int{2}
}

type GpioOtgMode int32

const (
	GpioOtgMode_OFF GpioOtgMode = 0
	GpioOtgMode_ON  GpioOtgMode = 1
)

// Enum value maps for GpioOtgMode.
var (
	GpioOtgMode_name = map[int32]string{
		0: "OFF",
		1: "ON",
	}
	GpioOtgMode_value = map[string]int32{
		"OFF": 0,
		"ON":  1,
	}
)

func (x GpioOtgMode) Enum() *GpioOtgMode {
	p := new(GpioOtgMode)
	*p = x
	return p
}

func (x GpioOtgMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GpioOtgMode) Descriptor() protoreflect.EnumDescriptor {
	return file_gpio_proto_enumTypes[3].Descriptor()
}

func (GpioOtgMode) Type() protoreflect.EnumType {
	return &file_gpio_proto_enumTypes[3]
}

func (x GpioOtgMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GpioOtgMode.Descriptor instead.
func (GpioOtgMode) EnumDescriptor() ([]byte, []int) {
	return file_gpio_proto_rawDescGZIP(), []int{3}
}

type SetPinMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pin  GpioPin     `protobuf:"varint,1,opt,name=pin,proto3,enum=PB_Gpio.GpioPin" json:"pin,omitempty"`
	Mode GpioPinMode `protobuf:"varint,2,opt,name=mode,proto3,enum=PB_Gpio.GpioPinMode" json:"mode,omitempty"`
}

func (x *SetPinMode) Reset() {
	*x = SetPinMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPinMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPinMode) ProtoMessage() {}

func (x *SetPinMode) ProtoReflect() protoreflect.Message {
	mi := &file_gpio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPinMode.ProtoReflect.Descriptor instead.
func (*SetPinMode) Descriptor() ([]byte, []int) {
	return file_gpio_proto_rawDescGZIP(), []int{0}
}

func (x *SetPinMode) GetPin() GpioPin {
	if x != nil {
		return x.Pin
	}
	return GpioPin_PC0
}

func (x *SetPinMode) GetMode() GpioPinMode {
	if x != nil {
		return x.Mode
	}
	return GpioPinMode_OUTPUT
}

type SetInputPull struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pin      GpioPin       `protobuf:"varint,1,opt,name=pin,proto3,enum=PB_Gpio.GpioPin" json:"pin,omitempty"`
	PullMode GpioInputPull `protobuf:"varint,2,opt,name=pull_mode,json=pullMode,proto3,enum=PB_Gpio.GpioInputPull" json:"pull_mode,omitempty"`
}

func (x *SetInputPull) Reset() {
	*x = SetInputPull{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpio_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetInputPull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInputPull) ProtoMessage() {}

func (x *SetInputPull) ProtoReflect() protoreflect.Message {
	mi := &file_gpio_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInputPull.ProtoReflect.Descriptor instead.
func (*SetInputPull) Descriptor() ([]byte, []int) {
	return file_gpio_proto_rawDescGZIP(), []int{1}
}

func (x *SetInputPull) GetPin() GpioPin {
	if x != nil {
		return x.Pin
	}
	return GpioPin_PC0
}

func (x *SetInputPull) GetPullMode() GpioInputPull {
	if x != nil {
		return x.PullMode
	}
	return GpioInputPull_NO
}

type GetPinMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pin GpioPin `protobuf:"varint,1,opt,name=pin,proto3,enum=PB_Gpio.GpioPin" json:"pin,omitempty"`
}

func (x *GetPinMode) Reset() {
	*x = GetPinMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpio_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPinMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPinMode) ProtoMessage() {}

func (x *GetPinMode) ProtoReflect() protoreflect.Message {
	mi := &file_gpio_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPinMode.ProtoReflect.Descriptor instead.
func (*GetPinMode) Descriptor() ([]byte, []int) {
	return file_gpio_proto_rawDescGZIP(), []int{2}
}

func (x *GetPinMode) GetPin() GpioPin {
	if x != nil {
		return x.Pin
	}
	return GpioPin_PC0
}

type GetPinModeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode GpioPinMode `protobuf:"varint,1,opt,name=mode,proto3,enum=PB_Gpio.GpioPinMode" json:"mode,omitempty"`
}

func (x *GetPinModeResponse) Reset() {
	*x = GetPinModeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpio_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPinModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPinModeResponse) ProtoMessage() {}

func (x *GetPinModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpio_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPinModeResponse.ProtoReflect.Descriptor instead.
func (*GetPinModeResponse) Descriptor() ([]byte, []int) {
	return file_gpio_proto_rawDescGZIP(), []int{3}
}

func (x *GetPinModeResponse) GetMode() GpioPinMode {
	if x != nil {
		return x.Mode
	}
	return GpioPinMode_OUTPUT
}

type ReadPin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pin GpioPin `protobuf:"varint,1,opt,name=pin,proto3,enum=PB_Gpio.GpioPin" json:"pin,omitempty"`
}

func (x *ReadPin) Reset() {
	*x = ReadPin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpio_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadPin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPin) ProtoMessage() {}

func (x *ReadPin) ProtoReflect() protoreflect.Message {
	mi := &file_gpio_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPin.ProtoReflect.Descriptor instead.
func (*ReadPin) Descriptor() ([]byte, []int) {
	return file_gpio_proto_rawDescGZIP(), []int{4}
}

func (x *ReadPin) GetPin() GpioPin {
	if x != nil {
		return x.Pin
	}
	return GpioPin_PC0
}

type ReadPinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint32 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ReadPinResponse) Reset() {
	*x = ReadPinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpio_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadPinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPinResponse) ProtoMessage() {}

func (x *ReadPinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpio_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPinResponse.ProtoReflect.Descriptor instead.
func (*ReadPinResponse) Descriptor() ([]byte, []int) {
	return file_gpio_proto_rawDescGZIP(), []int{5}
}

func (x *ReadPinResponse) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type WritePin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pin   GpioPin `protobuf:"varint,1,opt,name=pin,proto3,enum=PB_Gpio.GpioPin" json:"pin,omitempty"`
	Value uint32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *WritePin) Reset() {
	*x = WritePin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpio_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WritePin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WritePin) ProtoMessage() {}

func (x *WritePin) ProtoReflect() protoreflect.Message {
	mi := &file_gpio_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WritePin.ProtoReflect.Descriptor instead.
func (*WritePin) Descriptor() ([]byte, []int) {
	return file_gpio_proto_rawDescGZIP(), []int{6}
}

func (x *WritePin) GetPin() GpioPin {
	if x != nil {
		return x.Pin
	}
	return GpioPin_PC0
}

func (x *WritePin) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetOtgMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetOtgMode) Reset() {
	*x = GetOtgMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpio_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOtgMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOtgMode) ProtoMessage() {}

func (x *GetOtgMode) ProtoReflect() protoreflect.Message {
	mi := &file_gpio_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOtgMode.ProtoReflect.Descriptor instead.
func (*GetOtgMode) Descriptor() ([]byte, []int) {
	return file_gpio_proto_rawDescGZIP(), []int{7}
}

type GetOtgModeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode GpioOtgMode `protobuf:"varint,1,opt,name=mode,proto3,enum=PB_Gpio.GpioOtgMode" json:"mode,omitempty"`
}

func (x *GetOtgModeResponse) Reset() {
	*x = GetOtgModeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpio_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOtgModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOtgModeResponse) ProtoMessage() {}

func (x *GetOtgModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpio_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOtgModeResponse.ProtoReflect.Descriptor instead.
func (*GetOtgModeResponse) Descriptor() ([]byte, []int) {
	return file_gpio_proto_rawDescGZIP(), []int{8}
}

func (x *GetOtgModeResponse) GetMode() GpioOtgMode {
	if x != nil {
		return x.Mode
	}
	return GpioOtgMode_OFF
}

type SetOtgMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode GpioOtgMode `protobuf:"varint,1,opt,name=mode,proto3,enum=PB_Gpio.GpioOtgMode" json:"mode,omitempty"`
}

func (x *SetOtgMode) Reset() {
	*x = SetOtgMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpio_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOtgMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOtgMode) ProtoMessage() {}

func (x *SetOtgMode) ProtoReflect() protoreflect.Message {
	mi := &file_gpio_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOtgMode.ProtoReflect.Descriptor instead.
func (*SetOtgMode) Descriptor() ([]byte, []int) {
	return file_gpio_proto_rawDescGZIP(), []int{9}
}

func (x *SetOtgMode) GetMode() GpioOtgMode {
	if x != nil {
		return x.Mode
	}
	return GpioOtgMode_OFF
}

var File_gpio_proto protoreflect.FileDescriptor

var file_gpio_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x70, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x50, 0x42,
	0x5f, 0x47, 0x70, 0x69, 0x6f, 0x22, 0x5a, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x50, 0x69, 0x6e, 0x4d,
	0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x70, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x10, 0x2e, 0x50, 0x42, 0x5f, 0x47, 0x70, 0x69, 0x6f, 0x2e, 0x47, 0x70, 0x69, 0x6f, 0x50,
	0x69, 0x6e, 0x52, 0x03, 0x70, 0x69, 0x6e, 0x12, 0x28, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x50, 0x42, 0x5f, 0x47, 0x70, 0x69, 0x6f, 0x2e,
	0x47, 0x70, 0x69, 0x6f, 0x50, 0x69, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x22, 0x67, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x50, 0x75, 0x6c,
	0x6c, 0x12, 0x22, 0x0a, 0x03, 0x70, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x50, 0x42, 0x5f, 0x47, 0x70, 0x69, 0x6f, 0x2e, 0x47, 0x70, 0x69, 0x6f, 0x50, 0x69, 0x6e,
	0x52, 0x03, 0x70, 0x69, 0x6e, 0x12, 0x33, 0x0a, 0x09, 0x70, 0x75, 0x6c, 0x6c, 0x5f, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x50, 0x42, 0x5f, 0x47, 0x70,
	0x69, 0x6f, 0x2e, 0x47, 0x70, 0x69, 0x6f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x50, 0x75, 0x6c, 0x6c,
	0x52, 0x08, 0x70, 0x75, 0x6c, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x30, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x50, 0x69, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x70, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x50, 0x42, 0x5f, 0x47, 0x70, 0x69, 0x6f, 0x2e,
	0x47, 0x70, 0x69, 0x6f, 0x50, 0x69, 0x6e, 0x52, 0x03, 0x70, 0x69, 0x6e, 0x22, 0x3e, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x50, 0x69, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x14, 0x2e, 0x50, 0x42, 0x5f, 0x47, 0x70, 0x69, 0x6f, 0x2e, 0x47, 0x70, 0x69, 0x6f, 0x50,
	0x69, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x2d, 0x0a, 0x07,
	0x52, 0x65, 0x61, 0x64, 0x50, 0x69, 0x6e, 0x12, 0x22, 0x0a, 0x03, 0x70, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x50, 0x42, 0x5f, 0x47, 0x70, 0x69, 0x6f, 0x2e, 0x47,
	0x70, 0x69, 0x6f, 0x50, 0x69, 0x6e, 0x52, 0x03, 0x70, 0x69, 0x6e, 0x22, 0x27, 0x0a, 0x0f, 0x52,
	0x65, 0x61, 0x64, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x44, 0x0a, 0x08, 0x57, 0x72, 0x69, 0x74, 0x65, 0x50, 0x69, 0x6e,
	0x12, 0x22, 0x0a, 0x03, 0x70, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x50, 0x42, 0x5f, 0x47, 0x70, 0x69, 0x6f, 0x2e, 0x47, 0x70, 0x69, 0x6f, 0x50, 0x69, 0x6e, 0x52,
	0x03, 0x70, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x4f, 0x74, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x3e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4f,
	0x74, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28,
	0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x50,
	0x42, 0x5f, 0x47, 0x70, 0x69, 0x6f, 0x2e, 0x47, 0x70, 0x69, 0x6f, 0x4f, 0x74, 0x67, 0x4d, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x36, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x4f,
	0x74, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x50, 0x42, 0x5f, 0x47, 0x70, 0x69, 0x6f, 0x2e, 0x47,
	0x70, 0x69, 0x6f, 0x4f, 0x74, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x2a, 0x51, 0x0a, 0x07, 0x47, 0x70, 0x69, 0x6f, 0x50, 0x69, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x50,
	0x43, 0x30, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x43, 0x31, 0x10, 0x01, 0x12, 0x07, 0x0a,
	0x03, 0x50, 0x43, 0x33, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x42, 0x32, 0x10, 0x03, 0x12,
	0x07, 0x0a, 0x03, 0x50, 0x42, 0x33, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x41, 0x34, 0x10,
	0x05, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x41, 0x36, 0x10, 0x06, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x41,
	0x37, 0x10, 0x07, 0x2a, 0x24, 0x0a, 0x0b, 0x47, 0x70, 0x69, 0x6f, 0x50, 0x69, 0x6e, 0x4d, 0x6f,
	0x64, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x55, 0x54, 0x50, 0x55, 0x54, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x10, 0x01, 0x2a, 0x29, 0x0a, 0x0d, 0x47, 0x70, 0x69,
	0x6f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x50, 0x75, 0x6c, 0x6c, 0x12, 0x06, 0x0a, 0x02, 0x4e, 0x4f,
	0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x50, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f,
	0x57, 0x4e, 0x10, 0x02, 0x2a, 0x1e, 0x0a, 0x0b, 0x47, 0x70, 0x69, 0x6f, 0x4f, 0x74, 0x67, 0x4d,
	0x6f, 0x64, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x46, 0x46, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02,
	0x4f, 0x4e, 0x10, 0x01, 0x42, 0x22, 0x0a, 0x20, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6c, 0x69, 0x70,
	0x70, 0x65, 0x72, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x67, 0x70, 0x69, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gpio_proto_rawDescOnce sync.Once
	file_gpio_proto_rawDescData = file_gpio_proto_rawDesc
)

func file_gpio_proto_rawDescGZIP() []byte {
	file_gpio_proto_rawDescOnce.Do(func() {
		file_gpio_proto_rawDescData = protoimpl.X.CompressGZIP(file_gpio_proto_rawDescData)
	})
	return file_gpio_proto_rawDescData
}

var file_gpio_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_gpio_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_gpio_proto_goTypes = []interface{}{
	(GpioPin)(0),               // 0: PB_Gpio.GpioPin
	(GpioPinMode)(0),           // 1: PB_Gpio.GpioPinMode
	(GpioInputPull)(0),         // 2: PB_Gpio.GpioInputPull
	(GpioOtgMode)(0),           // 3: PB_Gpio.GpioOtgMode
	(*SetPinMode)(nil),         // 4: PB_Gpio.SetPinMode
	(*SetInputPull)(nil),       // 5: PB_Gpio.SetInputPull
	(*GetPinMode)(nil),         // 6: PB_Gpio.GetPinMode
	(*GetPinModeResponse)(nil), // 7: PB_Gpio.GetPinModeResponse
	(*ReadPin)(nil),            // 8: PB_Gpio.ReadPin
	(*ReadPinResponse)(nil),    // 9: PB_Gpio.ReadPinResponse
	(*WritePin)(nil),           // 10: PB_Gpio.WritePin
	(*GetOtgMode)(nil),         // 11: PB_Gpio.GetOtgMode
	(*GetOtgModeResponse)(nil), // 12: PB_Gpio.GetOtgModeResponse
	(*SetOtgMode)(nil),         // 13: PB_Gpio.SetOtgMode
}
var file_gpio_proto_depIdxs = []int32{
	0,  // 0: PB_Gpio.SetPinMode.pin:type_name -> PB_Gpio.GpioPin
	1,  // 1: PB_Gpio.SetPinMode.mode:type_name -> PB_Gpio.GpioPinMode
	0,  // 2: PB_Gpio.SetInputPull.pin:type_name -> PB_Gpio.GpioPin
	2,  // 3: PB_Gpio.SetInputPull.pull_mode:type_name -> PB_Gpio.GpioInputPull
	0,  // 4: PB_Gpio.GetPinMode.pin:type_name -> PB_Gpio.GpioPin
	1,  // 5: PB_Gpio.GetPinModeResponse.mode:type_name -> PB_Gpio.GpioPinMode
	0,  // 6: PB_Gpio.ReadPin.pin:type_name -> PB_Gpio.GpioPin
	0,  // 7: PB_Gpio.WritePin.pin:type_name -> PB_Gpio.GpioPin
	3,  // 8: PB_Gpio.GetOtgModeResponse.mode:type_name -> PB_Gpio.GpioOtgMode
	3,  // 9: PB_Gpio.SetOtgMode.mode:type_name -> PB_Gpio.GpioOtgMode
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_gpio_proto_init() }
func file_gpio_proto_init() {
	if File_gpio_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gpio_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPinMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpio_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetInputPull); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpio_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPinMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpio_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPinModeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpio_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadPin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpio_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadPinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpio_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WritePin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpio_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOtgMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpio_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOtgModeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpio_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetOtgMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gpio_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gpio_proto_goTypes,
		DependencyIndexes: file_gpio_proto_depIdxs,
		EnumInfos:         file_gpio_proto_enumTypes,
		MessageInfos:      file_gpio_proto_msgTypes,
	}.Build()
	File_gpio_proto = out.File
	file_gpio_proto_rawDesc = nil
	file_gpio_proto_goTypes = nil
	file_gpio_proto_depIdxs = nil
}
